services:
  mongodb:
    image: mongo:8.0.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    platform: linux/arm64
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourPassword123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  pentaho:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: pentaho
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - ./pdi-files:/opt/pdi-cache
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - mongodb
      - sqlserver

volumes:
  sqlserver_data:
  mongodb_data:
