services:
  mongodb:
    image: mongo:8.0.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    platform: linux/arm64
    container_name: sqlserver
    environment:
      SA_PASSWORD: "P@ssw0rd123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver_data:/var/opt/mssql

  webspoon:
    image: hiromuhota/webspoon:latest
    container_name: webspoon
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - PDI_VERSION=9.3
      - TZ=UTC
    volumes:
      - ./pdi-files:/home/pentaho/.pentaho
      - ./pdi-jobs:/var/lib/pdi-jobs

volumes:
  sqlserver_data:
  mongodb_data:
